name: MayList
description: May List application that allows users to create task lists or checklists. With May List, users can easily add and delete items in their list with an easy-to-use and simple interface.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  motion_toast: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/icon/
  fonts:
  - family: Poppins
    fonts:
    - asset: assets/fonts/Poppins/Poppins-Italic.ttf
    - asset: assets/fonts/Poppins/Poppins-Light.ttf
    - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
